import dotenv from "dotenv";
dotenv.config();

// Read-only functions
export {
  canRegisterName,
  getLastTokenId,
  getRenewalHeight,
  canResolveName,
  getOwner,
  getOwnerById,
  getNamespacePrice,
  getNamePrice,
  canNamespaceBeRegistered,
  getNamespaceProperties,
  getNameInfo,
  getBnsFromId,
  getPrimaryName,
  resolveName,
  fetchUserOwnedNames,
  resolveNameZonefile,
} from "./readOnlyCalls";

// Contract interaction functions
export {
  buildTransferNameTx,
  buildListInUstxTx,
  buildUnlistInUstxTx,
  buildBuyInUstxTx,
  buildSetPrimaryNameTx,
  buildFreezeManagerTx,
  buildPreorderNamespaceTx,
  buildRevealNamespaceTx,
  buildLaunchNamespaceTx,
  buildTurnOffManagerTransfersTx,
  buildImportNameTx,
  buildNamespaceUpdatePriceTx,
  buildNamespaceFreezePriceTx,
  buildNameClaimFastTx,
  buildPreorderNameTx,
  buildRegisterNameTx,
  buildPreviousRegisterNameTx,
  buildClaimPreorderTx,
  buildRenewNameTx,
  buildUpdateZonefileTx,
} from "./contractCalls";

// Types
export type {
  PriceFunction,
  BnsContractCallOptions,
  BnsContractCallOptionsExecution,
  BnsReadOnlyOptions,
  CanRegisterNameOptions,
  GetLastTokenIdOptions,
  GetRenewalHeightOptions,
  CanResolveNameOptions,
  GetOwnerOptions,
  GetNamespacePriceOptions,
  GetNamePriceOptions,
  CanNamespaceBeRegisteredOptions,
  GetNamespacePropertiesOptions,
  NamespaceProperties,
  NameInfo,
  GetIdFromBnsOptions,
  GetBnsFromIdOptions,
  GetPrimaryNameOptions,
  TransferNameOptions,
  ListInUstxOptions,
  UnlistInUstxOptions,
  BuyInUstxOptions,
  SetPrimaryNameOptions,
  FreezeManagerOptions,
  PreorderNamespaceOptions,
  RevealNamespaceOptions,
  LaunchNamespaceOptions,
  TurnOffManagerTransfersOptions,
  ImportNameOptions,
  NamespaceUpdatePriceOptions,
  NamespaceFreezePriceOptions,
  NameFastClaimOptions,
  PreorderNameOptions,
  RegisterNameOptions,
  ClaimPreorderOptions,
  RenewNameOptions,
  ResolveNameOptions,
  FetchUserOwnedNamesOptions,
  UpdateZonefileOptions,
  Subdomain,
  ZonefileData,
} from "./interfaces";
